"""Create account and meal data tables

Revision ID: a1b938ef9cc7
Revises:
Create Date: 2026-10-07 23:47:53.764835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b938ef9cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('basket_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('cuisine', sa.String(length=120), nullable=False),
    sa.Column('meal_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_basket_price_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_basket_quantity_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meal_id', name='uq_basket_user_meal')
    )
    with op.batch_alter_table('basket_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_basket_items_user_id'), ['user_id'], unique=False)

    op.create_table('favorite_meals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('cuisine', sa.String(length=120), nullable=False),
    sa.Column('meal_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meal_id', name='uq_favorite_user_meal')
    )
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_meals_user_id'), ['user_id'], unique=False)

    op.create_table('planned_meals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=9), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('cuisine', sa.String(length=120), nullable=False),
    sa.Column('meal_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("day IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')", name='ck_planned_meal_day'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'meal_id', name='uq_planned_user_day_meal')
    )
    with op.batch_alter_table('planned_meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_meals_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_meals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_meals_user_id'))
        batch_op.drop_index(batch_op.f('ix_planned_meals_day'))

    op.drop_table('planned_meals')
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_meals_user_id'))

    op.drop_table('favorite_meals')
    with op.batch_alter_table('basket_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_basket_items_user_id'))

    op.drop_table('basket_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
